/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRightsProtocol,
  IRightsProtocolInterface,
} from "../IRightsProtocol";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenID",
        type: "uint256",
      },
    ],
    name: "rightsURIs",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRightsProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): IRightsProtocolInterface {
    return new utils.Interface(_abi) as IRightsProtocolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRightsProtocol {
    return new Contract(address, _abi, signerOrProvider) as IRightsProtocol;
  }
}
